version: 2.1
orbs:
  flutter: circleci/flutter@1.1.0
jobs:
  setup_env_files:
    docker:
      - image: cimg/base:2022.05
    steps:
      - run:
          command: |
              echo apiKey=$API_KEY > $USER.env
              ls
workflows:
  test:
    jobs:
      - setup_env_files
      - flutter/unit_test:
          version: 3.3.3
          requires:
            - setup_env_files