version: 2.1
orbs:
  flutter: circleci/flutter@1.1.0
jobs:
  setup_env_files:
    docker:
      - image: cirrusci/flutter:3.3.3
    steps:
      - checkout
      - run:
          command: |
              touch .env
              echo "apiKey=${API_KEY}" >> .env
              ls
workflows:
  test:
    jobs:
      - setup_env_files
      - flutter/unit_test:
          version: 3.3.3
          requires:
            - setup_env_files