version: 2.1
jobs:
  build_all:
    docker:
      - image: cirrusci/flutter:3.3.3
    steps:
      - checkout
      - run: flutter doctor
      - run: flutter pub get
      - run: flutter pub run build_runner build
      - run: flutter analyze lib
      - run: flutter test
  build_release:
    docker:
      - image: cirrusci/flutter:3.3.3
    steps:
      - run:
          name: Keystore variables
          command: |
            echo "$GOOGLE_PLAY_KEY" > "android/playstore.json"
            echo "$RELEASE_KEYSTORE_BASE64" | base64 --decode > "android/app/release_keystore.jks"
      - run:
          name: Build Android release
          command: cd ~/ && flutter build apk
      - store_artifacts:
          path: android/app/build/outputs/apk/release/app-release.apk
          destination: artifact-file
      - run:
          name: Install Gem dependencies for android Fastfile
          command: bundle install
          working_directory: ~/android
      - run:
          name: Upload to Google App Store
          command: cd android && bundle exec fastlane playstore --verbose
workflows:
  version: 2
  build:
    jobs:
      - build_all
      - build_release:
          requires:
            - build_all
          filters:
            branches:
              only:
                - master
                - CD_integration