version: 2.1
orbs:
  flutter: circleci/flutter@1.1.0
jobs:
  setup_env_files:
    docker:
      - image: cimg/base:2022.05
    steps:
      - run:
          command: echo apiKey=$API_KEY > .env
      - run:
          command: echo apiKey=123456 > /test/resources/test_res.env
workflows:
  test:
    jobs:
      - setup_env_files
      - flutter/unit_test:
          version: 3.3.3
          requires:
            - setup_env_files