version: 2.1
orbs:
  flutter: circleci/flutter@1.1.0
commands:
  setup_env_files:
    description: "build .env files for"
    steps:
      - run: echo apiKey=$API_KEY > .env
      - run: echo apiKey=123456 > test/resources/test_res.env
workflows:
  test:
    jobs:
      - setup_env_files
      - flutter/unit_test:
          version: 3.3.3