version: 2.1

orbs:
  android: circleci/android@2.1.2
  flutter-orb-latest: souravjangra/flutter-orb-latest@0.0.2
#  flutter-orb: circleci/flutter@1.1.0
  ruby: circleci/ruby@1.8.0
  docker: circleci/docker@2.1.3

jobs:
  integration_test_android:
    executor:
      name: android/android-machine
      resource-class: xlarge
      tag: 2022.03.1
    steps:
      - checkout
      - flutter-orb-latest/install_sdk_and_pub:
          cache-version: machine
          flutter_version: 2.10.3
      - android/create-avd:
          avd-name: flutter
          install: true
          system-image: system-images;android-29;default;x86
      - android/start-emulator:
          avd-name: flutter
          post-emulator-launch-assemble-command: 'flutter build apk --debug'
          restore-gradle-cache-find-args: ./android -name 'build.gradle'
      - android/run-tests:
          test-command: flutter drive --target=test/widget_test.dart
      - store_artifacts:
          path: ozzie

  distribute_android:
    executor:
      name: android/android-docker
      resource-class: xlarge
      tag: 2022.03.1
    steps:
      - checkout
      - flutter-orb-latest/install_sdk_and_pub:
          cache-version: docker
          flutter_version: 2.10.3
      - flutter-orb-latest/install_android_gradle
      - ruby/install-deps:
          app-dir: android
          key: android
      - run:
          command: bundle exec fastlane distribute_debug
          working_directory: android

workflows:
  test_and_distribute:
    jobs:
      - flutter-orb-latest/unit_test:
          version: 2.10.3
      - flutter-orb-latest/lint:
          version: 2.10.3
      - integration_test_android
      - distribute_android:
          context: # Context
            - mobile