import 'package:easy_cc_flutter/BaseViewModel.dart';
import 'package:easy_cc_flutter/Utils/SelectionType.dart';

class MainViewModel extends BaseViewmodel {

  double conversionRate = 1.4;

  final List<String> data = <String>['ALL - Albanian Lek',
    'AFN - Afghan Afghani',
    'DZD - Algerian Dinar',
    'AOA - Angolan Kwanza',
    'ARS - Argentine Peso',
    'AMD - Armenian Dram',
    'AWG - Aruban Florin',
    'AUD - Australian Dollar',
    'AZN - Azerbaijani Manat',
    'BSD - Bahamian Dollar',
    'BHD - Bahraini Dinar',
    'BDT - Bangladeshi Taka',
    'BBD - Barbadian Dollar',
    'BYR - Belarusian Ruble',
    'BZD - Belize Dollar',
    'BTN - Bhutanese Ngultrum',
    'BTC - Bitcoin',
    'BOB - Bolivian Boliviano',
    'BAM - Bosnia And Herzegovina Konvertibilna Marka',
    'BWP - Botswana Pula',
    'BRL - Brazilian Real',
    'GBP - British Pound',
    'BND - Brunei Dollar',
    'BGN - Bulgarian Lev',
    'BIF - Burundi Franc',
    'KHR - Cambodian Riel',
    'CAD - Canadian Dollar',
    'CVE - Cape Verdean Escudo',
    'KYD - Cayman Islands Dollar',
    'XAF - Central African CFA Franc',
    'XPF - CFP Franc',
    'CLP - Chilean Peso',
    'CNY - Chinese Yuan',
    'COP - Colombian Peso',
    'KMF - Comorian Franc',
    'CDF - Congolese Franc',
    'CRC - Costa Rican Colon',
    'HRK - Croatian Kuna',
    'CUP - Cuban Peso',
    'CZK - Czech Koruna',
    'DKK - Danish Krone',
    'DJF - Djiboutian Franc',
    'DOP - Dominican Peso',
    'XCD - East Caribbean Dollar',
    'EGP - Egyptian Pound',
    'ERN - Eritrean Nakfa',
    'ETB - Ethiopian Birr',
    'EUR - Euro',
    'FKP - Falkland Islands Pound',
    'FJD - Fijian Dollar',
    'GMD - Gambian Dalasi',
    'GEL - Georgian Lari',
    'GHS - Ghanaian Cedi',
    'GIP - Gibraltar Pound',
    'GTQ - Guatemalan Quetzal',
    'GNF - Guinean Franc',
    'GYD - Guyanese Dollar',
    'HTG - Haitian Gourde',
    'HNL - Honduran Lempira',
    'HKD - Hong Kong Dollar',
    'HUF - Hungarian Forint',
    'ISK - Icelandic Kr\u00f3na',
    'INR - Indian Rupee',
    'IDR - Indonesian Rupiah',
    'IRR - Iranian Rial',
    'IQD - Iraqi Dinar',
    'ILS - Israeli New Sheqel',
    'JMD - Jamaican Dollar',
    'JPY - Japanese Yen',
    'JOD - Jordanian Dinar',
    'KZT - Kazakhstani Tenge',
    'KES - Kenyan Shilling',
    'KWD - Kuwaiti Dinar',
    'KGS - Kyrgyzstani Som',
    'LAK - Lao Kip',
    'LVL - Latvian Lats',
    'LBP - Lebanese Lira',
    'LSL - Lesotho Loti',
    'LRD - Liberian Dollar',
    'LYD - Libyan Dinar',
    'MOP - Macanese Pataca',
    'MKD - Macedonian Denar',
    'MGA - Malagasy Ariary',
    'MWK - Malawian Kwacha',
    'MYR - Malaysian Ringgit',
    'MVR - Maldivian Rufiyaa',
    'MRO - Mauritanian Ouguiya',
    'MUR - Mauritian Rupee',
    'MXN - Mexican Peso',
    'MDL - Moldovan Leu',
    'MNT - Mongolian Tugrik',
    'MAD - Moroccan Dirham',
    'MZN - Mozambican Metical',
    'MMK - Myanma Kyat',
    'NAD - Namibian Dollar',
    'NPR - Nepalese Rupee',
    'ANG - Netherlands Antillean Gulden',
    'TWD - New Taiwan Dollar',
    'NZD - New Zealand Dollar',
    'NIO - Nicaraguan Cordoba',
    'NGN - Nigerian Naira',
    'KPW - North Korean Won',
    'NOK - Norwegian Krone',
    'OMR - Omani Rial',
    'TOP - Paanga',
    'PKR - Pakistani Rupee',
    'PAB - Panamanian Balboa',
    'PGK - Papua New Guinean Kina',
    'PYG - Paraguayan Guarani',
    'PEN - Peruvian Nuevo Sol',
    'PHP - Philippine Peso',
    'PLN - Polish Zloty',
    'QAR - Qatari Riyal',
    'RON - Romanian Leu',
    'RUB - Russian Ruble',
    'RWF - Rwandan Franc',
    'SHP - Saint Helena Pound',
    'WST - Samoan Tala',
    'STD - Sao Tome And Principe Dobra',
    'SAR - Saudi Riyal',
    'RSD - Serbian Dinar',
    'SCR - Seychellois Rupee',
    'SLL - Sierra Leonean Leone',
    'SGD - Singapore Dollar',
    'SBD - Solomon Islands Dollar',
    'SOS - Somali Shilling',
    'ZAR - South African Rand',
    'KRW - South Korean Won',
    'XDR - Special Drawing Rights',
    'LKR - Sri Lankan Rupee',
    'SDG - Sudanese Pound',
    'SRD - Surinamese Dollar',
    'SZL - Swazi Lilangeni',
    'SEK - Swedish Krona',
    'CHF - Swiss Franc',
    'SYP - Syrian Pound',
    'TJS - Tajikistani Somoni',
    'TZS - Tanzanian Shilling',
    'THB - Thai Baht',
    'TTD - Trinidad and Tobago Dollar',
    'TND - Tunisian Dinar',
    'TRY - Turkish New Lira',
    'TMT - Turkmenistan Manat',
    'AED - UAE Dirham',
    'UGX - Ugandan Shilling',
    'UAH - Ukrainian Hryvnia',
    'USD - United States Dollar',
    'UYU - Uruguayan Peso',
    'UZS - Uzbekistani Som',
    'VUV - Vanuatu Vatu',
    'VEF - Venezuelan Bolivar',
    'VND - Vietnamese Dong',
    'XOF - West African CFA Franc',
    'YER - Yemeni Rial',
    'ZMW - Zambian Kwacha'];

  String convertInput(String? input, SelectionType type) {
    if (input == null || input.isEmpty) {
      return "";
    }
    double convertedInput = double.parse(input);

    switch (type) {
      case SelectionType.conversionFrom:
        return (convertedInput * conversionRate).toStringAsFixed(2);
      case SelectionType.conversionTo:
        return (convertedInput / conversionRate).toStringAsFixed(2);
    }
  }
}